version: '3'

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: 'mysql'
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: agua-facil
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
volumes:
  database:
    driver: "local"